### ISSUE TITLE
How to support gestures to dismiss？

### ISSUE THREAD

**Issue by xhzengAIB** [xiekw2010/DXPopover#1]
@xiekw2010 

Hi!  How to support gestures to dismiss？

Jack

**Comment by xiekw2010** [comment]
It's not supported yet.

 It will be a little tricky when the contentView is kind of scrollview, I will work on that soon.

**Comment by cerupcat** [comment]
Any progress on this?

**Comment by diliplilaramani** [comment]
Hi, I added view controller on popover view and table view in my view controller but its crashing on table scroll and did select. Can you suggest something? Here is my code:

```
    var popover = DXPopover(frame: CGRectMake(0, 0, self.view.frame.size.width, self.view.frame.size.height))

    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let vc = storyboard.instantiateViewControllerWithIdentifier("menuVC") as! UIViewController
    vc.view.frame = CGRectMake(0, 0, self.view.frame.size.width, 400)

    popover.showAtView(menuIcon, popoverPostion: DXPopoverPosition.Down, withContentView: vc.view, inView: self.view)
```

**Comment by xiekw2010** [comment]
Hi @dilipajm , What's the crash reason on lldb, I suggest that your vc.view is out of bounds of you container view
