### ISSUE TITLE
popover's position is wrong.

### ISSUE THREAD

**Issue by YzStyle** [xiekw2010/DXPopover#6]
Hi,I put a button on the TableCell.When I clip the button,the popover position always is far away from the button.Do you have something to sovle my problem?  

Tips:I'm a Chinese,My English is bad

**Comment by xiekw2010** [comment]
你的代码和错误的截图发出来看看

**Comment by YzStyle** [comment]
已经弄好了，必须把控件相对于屏幕的CGPoint找到，才可以正确出现在指定位置上，谢谢。
